//import liraries
export const Images = {
  Logo: require('../assets/HomeScreen/SecondLogo.png'),
  Notifybell: require('../assets/HomeScreen/NotifyBell.png'),
  Face: require('../assets/HomeScreen/TopTab/Face.png'),
  Makeup: require('../assets/HomeScreen/TopTab/makeup.png'),
  Girl: require('../assets/HomeScreen/TopTab/Girl.png'),
  Nail: require('../assets/HomeScreen/TopTab/Nails.png'),
  Star: require('../assets/HomeScreen/TopTab/Star.png'),
  checklist:require('../assets/HomeScreen/TopTab/checklist.png'),
  CoroselBg: require('../assets/HomeScreen/TopTab/AllCategories/coroselbg.png'),
  RightArrow: require('../assets/HomeScreen/TopTab/AllCategories/RightArrow.png'),
  img1: require('../assets/timepass/image1.png'),
  img2: require('../assets/timepass/image2.png'),
  img3: require('../assets/timepass/image3.png'),
  img4: require('../assets/timepass/image4.png'),
  Img1: require('../assets/timepass/img1.png'),
  Img2: require('../assets/timepass/img2.png'),
  Img3: require('../assets/timepass/img3.png'),
  Img4: require('../assets/timepass/img4.png'),
  Img5: require('../assets/timepass/img5.png'),
  Img6: require('../assets/timepass/img6.png'),
  Img7: require('../assets/timepass/img7.png'),
  Apple: require('../assets/AuthScreen/PaymentOnboard/Apple.png'),
  Credit: require('../assets/AuthScreen/PaymentOnboard/Credit.png'),
  Debit: require('../assets/AuthScreen/PaymentOnboard/Debit.png'),
  Gift: require('../assets/AuthScreen/PaymentOnboard/Gift.png'),
  PayPal: require('../assets/AuthScreen/PaymentOnboard/PayPal.png'),
  Search: require('../assets/SearchScreen/search.png'),
  list: require('../assets/SearchScreen/list.png'),
  map:  require('../assets/SearchScreen/map.png'),
  heartEmpty:require('../assets/SearchScreen/heartEmpty.png'),
  heartFill:require('../assets/SearchScreen/heartFill.png'),
  sort:require('../assets/SearchScreen/Sort.png'),
  filter:require('../assets/SearchScreen/Filter.png'),
  home:require('../assets/BookingPage/Home.png'),
  plus:require('../assets/BookingPage/plus.png'),
  location:require('../assets/BookingPage/Location.png'),
  cross:require('../assets/BookingPage/cross.png'),
  bell:require('../assets/BookingPage/Bell.png'),
  bin:require('../assets/BookingPage/bin.png'),
  profile:require('../assets/BookingPage/profile.png'),
  filledplus:require('../assets/BookingPage/filledplus.png'),
  mapuser:require('../assets/BookingPage/MapUser.png'),
  smallsearch:require('../assets/BookingPage/smallsearch.png'),
  mylocation:require('../assets/BookingPage/mylocation.png'),
  back:require('../assets/AuthScreen/Back.png'),
  edit:require('../assets/BookingPage/edit.png'),
  crosspink:require('../assets/BookingPage/crosspink.png'),
  homebrown:require('../assets/BookingPage/homebrown.png'),
  homepink:require('../assets/BookingPage/homepink.png'),
  workbrown:require('../assets/BookingPage/workbrown.png'),
  workpink:require('../assets/BookingPage/workpink.png'),
  locbrown:require('../assets/BookingPage/locbrown.png'),
  locpink:require('../assets/BookingPage/locpink.png'),
  outbin:require('../assets/OrdersScreen/outbin.png'),
  dategrey:require('../assets/OrdersScreen/dategrey.png'),
  locgrey:require('../assets/OrdersScreen/locgrey.png'),
  backround:require('../assets/BookingPage/backround.png'),
  profround:require('../assets/ProfileIcons/profround.png'),
  faqround:require('../assets/ProfileIcons/faqround.png'),
  heartround:require('../assets/ProfileIcons/heartround.png'),
  helpround:require('../assets/ProfileIcons/helpround.png'),
  settinground:require('../assets/ProfileIcons/settinground.png'),
  walletround:require('../assets/ProfileIcons/walletround.png'),
  locround:require('../assets/ProfileIcons/locround.png'),
  lockround:require('../assets/ProfileIcons/lockround.png'),
  workround:require('../assets/ProfileIcons/workround.png'),
  homeround:require('../assets/ProfileIcons/homeround.png'),
  menudots:require('../assets/ProfileIcons/menudots.png'),
  deletebin:require('../assets/ProfileIcons/deletebin.png'),
  minusround:require('../assets/ProfileIcons/minusround.png'),
  erroralert:require('../assets/Errors/ErrorAlert.png'),
  warningsign:require('../assets/Errors/warningsign.png'),



};
