export const Strings = {
  loginAsUser: 'Login as User',
  logintext: 'Login',
  loginAsBusiness: 'Login as Business',
  forgot: 'Forgot Password?',
  Reset: 'Reset Password',
  NoAccount: `Don't have an account yet?`,
  HaveAccount: `Already have an account?`,
  signupText: 'Sign Up',
  signupAsBusiness: 'Sign Up as Business',
  Terms: 'Terms and Conditions',
  Agree: 'I agree to',
  Submit:'Submit',
  next:'Next',
  skip:'Skip',
  AddProfile:'Add a profile picture',
  promotions: 'Active Promotions',
  TopBussiness: 'Top Businesses',
  bussinessnm:'Business Name',
  ForgotInst: `Enter you email and we’ll send you instructions on how to reset your password.`,
  topprof:'Top Professionals',
  paymethod:'Add Payment Method',
  Debit:'Debit/Credit Card',
  Credit:'Credit',
  Gift:'Gift Card',
  Paypal:'PayPal',
  Applepay:'Apple Pay',
  addlater:'Add Later',
  nameoncard:'Name on card',
  cardexp:'Card Expiry',
  cardnum:'Card Number',
  CVV:'CVV',
  cardSV:'Save Card',
  recommended:'Recommended Businesses',
  sortby:'Sort by',
  priceHtoL:'Price: High to Low',
  priceLtoH:'Price: Low to High',
  bestrated:'Best Rated',
  mostPopular:'Most popular',
  distance:'Distance (Closest)',
  businessprfl:'Business Profile',
  homeservice:'Home Service Available',
  hairser:'Hair Services',
  hairprof:'Hair Professionals',
  stars:'5.0',
  rating:'(121 Reviews)',
  photos:'Photos',
  bookser:'Book Service',
  selectProfop:'Select Professionals (Optional)',
  selectProf:'Select Professionals',
  searchLocation:'Search Location',
  selectLoc:'Select Location',
  addaddress:'Add Address',
  selectProfDes:`Selecting professional is optional, we’ll select a professional for you if you choose not to select by yourself.`,
  flatNo:'Flat/Villa No.',
  building:'Building/Villa',
  street:'Street',
  area:'Area',
  buildingName:'Building/Villa',
  directions:'Direnctions',
  svLoc:'Save Location',
  confbooking:'Confirm Booking',
  reschedule:'Reschedule',
  resservice:'Reschedule Service'
};
