export const Strings = {
  loginAsUser: 'Login as User',
  loginAsBusiness: 'Login as Business',
  addProfile: 'Add a profile picture',
  next: 'Next',
  skip: 'Skip',
  businessAddress: 'Business Address',
  searchLocation: 'Search Location',
  selectLocation: 'Select Location',
  addressDetails: 'Address Details',
  locationName: 'Location name',
  flatNo: 'Flat/Villa No.',
  flatVilla: 'Flat/Villa here',
  building: 'Building/Villa',
  buildingName: 'Building name here',
  street: 'Street',
  streetName: 'Street name here',
  area: 'Area',
  areaName: 'Area name here',
  directions: 'Directions',
  businessTimings: 'Business Timings',
  saveLocationTime: 'Save Location and Timings',
  to: 'To',
  services: 'Services',
  servicesOffer: 'What services do you offer?',
  hair: 'Hair',
  makeup: 'Makeup',
  skincare: 'Skincare',
  nails: 'Nails',
  hairRemoval: 'Hair Removal',
  tanning: 'Tanning',
  finish: 'Finish',
  new: 'New',
  upcoming: 'Upcoming',
  newBookings: 'New Bookings',
  accept: 'Accept',
  reject: 'Reject',
  no: 'No',
  reschedule: 'Reschedule',
  home: 'Home',
  staff: 'Staff',
  orders: 'Orders',
  profile: 'Profile',
  new: 'New',
  upcoming: 'Upcoming',
  newBookings: 'New Bookings',
  rejectBookingRequest: 'Are you sure you want to reject this booking request?',
  upcomingBookings: 'Upcoming Bookings',
  orderDetail: 'Order Detail',
  customerInfo: 'Customer Information',
  detail: 'Detail',
  service: 'Service',
  price: 'Price',
  duration: 'Duration',
  appointmentDate: 'Appointment Date',
  appointmentTime: 'Appointment Time',
  professional: 'Professional',
  serviceLocation: 'Service Location',
  noteCustomer: 'Note from customer:',
  note: 'Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae eleifend ac.',
  detailedLocation: 'Detailed location goes here',
  addpaymentMethod: 'Add Paymnet Method',
  debitCreditCard: 'Debit/Credit Card',
  giftCard: 'Gift Card',
  payPal: 'PayPal',
  applePay: 'Apple Pay',
  addDebitCreditCard: 'Add Debit/Credit Card',
  nameOnCard : 'Name on card',
  cardNumber: 'Card Number',
  cardExpiry: 'Card Expiry',
  CVV :'CVV',
  saveCard :'Save card',
  addLater :'Add Later'
};
